Added nightly build

diff --git a/.github/workflows/releaser.yml b/.github/workflows/releaser.yml
--- a/.github/workflows/releaser.yml
+++ b/.github/workflows/releaser.yml
@@ -10,37 +10,59 @@ jobs:
     runs-on: windows-latest
     steps:
       - uses: actions/checkout@v3
-      # get version from pubspec.yaml
+      # get version from pubspec.yaml and check if release already exists
       - name: Get version
         id: get_version
         run: |
           $pattern = "version: (.*?) \#"
           $string = Get-Content pubspec.yaml
           $wsl2_manager_version = [regex]::match($string, $pattern).Groups[1].Value
-          Write-Output "::set-output name=version::$wsl2_manager_version"
-      - name: Echo version
-        run: |
-          echo ${{ steps.get_version.outputs.version }}
-      # check if release already exists
-      - uses: cardinalby/git-get-release-action@v1
-        name: Check if release exists
-        id: check_release
-        env:
-          GITHUB_TOKEN: ${{ github.token }}
-          with:
-          tag: v${{ steps.get_version.outputs.version }}
-      # if check_release step fails build
+          # Make web REST call to check if release already exists
+          $result = $(Invoke-RestMethod -Uri https://api.github.com/repos/bostrot/wsl2-distro-manager/releases/tags/v$wsl2_manager_version)
+          if ($result) {
+            Write-Error "Release v$wsl2_manager_version already exists."
+            exit 1
+          } else {
+            Write-Output "::set-output name=version::$wsl2_manager_version"
+            exit 0
+          }
+      # if get_version step does not fail just build nightly
       - uses: subosito/flutter-action@v2
-        if: ${{ steps.check_release.outcome == 'failure' }}
+        if: ${{ steps.get_version.outcome == 'success' }}
         with:
           channel: 'stable'
       - run: flutter config --enable-windows-desktop
-        if: ${{ steps.check_release.outcome == 'failure' }}
+        if: ${{ steps.get_version.outcome == 'success' }}
       - run: flutter build windows
-        if: ${{ steps.check_release.outcome == 'failure' }}
+        if: ${{ steps.get_version.outcome == 'success' }}
+      # create zip with dlls and build
+      - name: Create zip with dlls and build
+        if: ${{ steps.get_version.outcome == 'success' }}
+        run: |
+          Copy-Item -Path ./windows-dlls/* -Destination ./build/windows/runner/Release/
+          # version is current build number or workflow run number
+          $version = $env:GITHUB_RUN_NUMBER
+          Compress-Archive -Path ./build/windows/runner/Release/* -DestinationPath .\wsl2-distro-manager-v$version.zip
+      # create nightly release
+      - uses: actions/upload-artifact@v3
+        name: Create nightly release
+        if: ${{ steps.get_version.outcome == 'success' }}
+        with:
+          name: wsl2-distro-manager-v${{ env.GITHUB_RUN_NUMBER }}
+          path: |
+            ./build/windows/runner/Release/wsl2-distro-manager-v${{ env.GITHUB_RUN_NUMBER }}.zip
+      # if get_version step fails build
+      - uses: subosito/flutter-action@v2
+        if: ${{ steps.get_version.outcome == 'failure' }}
+        with:
+          channel: 'stable'
+      - run: flutter config --enable-windows-desktop
+        if: ${{ steps.get_version.outcome == 'failure' }}
+      - run: flutter build windows
+        if: ${{ steps.get_version.outcome == 'failure' }}
       # create release
       - name: Create release
-        if: ${{ steps.check_release.outcome == 'failure' }}
+        if: ${{ steps.get_version.outcome == 'failure' }}
         run: |
           Copy-Item -Path ./windows-dlls/* -Destination ./build/windows/runner/Release/
           Compress-Archive -Path ./build/windows/runner/Release/* -DestinationPath .\wsl2-distro-manager-v${{ steps.get_version.outputs.version }}.zip
